### ISSUE TITLE
Precio sugerido en el producto no sale ?

### ISSUE THREAD

**Issue by etruel** [etruel/fakturo#3]
Al entrar en el producto en las escalas de precio la columna de precio sugerido se ve vacía

**Comment by manuelge** [comment]
Estuve testeando nuevamente y el problema aun sigue.

El precio sugerido solo se muestra al ingresar o modificar el costo del producto.

Es probable que tenga una validación JS para mostrar el precio sugerido solo cuando el valor del campo costo de producto cambie por eso al entrar en el edit no se ve sino hasta modificar el costo.

![new-product](https://user-images.githubusercontent.com/31927829/181624672-dbafd50e-609e-466c-bbf6-33a56d0c124a.jpeg)
![edit-product](https://user-images.githubusercontent.com/31927829/181624682-5debe8c1-5017-4ddb-9101-b8b3a53a7163.jpeg)
