### ISSUE TITLE
Some PHP Deprecated and Warnings

### ISSUE THREAD

**Issue by manuelge** [etruel/fakturo#37]
In the Stock screen from **Products>Stock** this warning is displayed:
Warning: Undefined variable $currencies in /var/www/clients/client1/web58/web/wp-content/plugins/fakturo/includes/taxonomy/stocks.php on line 156

In **Settings>System Settings** this deprecated is displayed:
Deprecated: strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/clients/client1/web58/web/wp-admin/admin-header.php on line 36

**Comment by gerarjos14** [comment]
I fix them, it is in my fork
