### ISSUE TITLE
Agregar los filtros de fecha en todos los reportes y corregir los que no funcionan correctamente.

### ISSUE THREAD

**Issue by manuelge** [etruel/fakturo#49]
**Trimestres**

1- De enero a marzo
2- De abril a junio
3- De julio a septiembre 
4- De octubre a diciembre

**1- Filtro "Este trimestre"**

Este filtro muestra los meses octubre, noviembre y diciembre, tanto en reporte de ventas como en los clientes, más abajo explico como deberia funcionar.
<img width="1410" alt="image" src="https://github.com/user-attachments/assets/de8f8ffd-afff-4c38-9c46-9b5f9aef1bfc">

**El funcionamiento debe ser:**

Debe mostrar el reporte del trimestre en el que te encuentras, por ejemplo si es hoy (Septiembre) debe mostrar los datos del trimestre 3, desde Julio hasta lo que va de Septiembre.

---

**2- Filtro "Ultimo trimestre"**
Actualmente el filtro está mostrando el mes actual y los dos meses anteriores (el trimestre actual).
![image](https://github.com/user-attachments/assets/3d6c82d7-d345-40eb-88de-6dfd003bc43b)

**El funcionamiento debe ser:**

Dependiendo del trimestre en el que te encuentras debe mostrar el trimestre anterior, por ejemplo si es hoy (Septiembre) debe mostrar los datos del trimestre 2, desde Abril hasta Junio

---

**3- Filtro "personalizado"**
Este filtro que deberia ser para buscar por rangos de fecha no está funcionando, deberia agregar dos campos date para elegir los rangos de fecha, esto debe ser igual para todos los reportes.
<img width="1400" alt="image" src="https://github.com/user-attachments/assets/96724281-3c5f-4736-a867-68ec0ff6551b">

**Comment by etruel** [comment]
Los datos del filtro deben mostrarse en la cabecera del reporte al ejecutar el filtro. (Actualmente muestra las fechas de 1970.)
