### ISSUE TITLE
Revisar el responsive del grafico de reportes

### ISSUE THREAD

**Issue by manuelge** [etruel/fakturo#50]
Estudiar y ver las posibles soluciones para corregir el grafico en responsive, este grafico es generado en un "canvas" por lo que los estilos del css no le afectan directamente.

Actualmente en responsive los numeros de la columna izquierda se van ocultando dependiendo del tamaño de la pantalla haciendo que se dañe el diseño.

**Pantalla normal:**
<img width="939" alt="image" src="https://github.com/user-attachments/assets/e13e0257-79ba-4b89-ab93-590272ab4b8f">

**Tablet:**
<img width="483" alt="image" src="https://github.com/user-attachments/assets/c9a5fc02-4230-435b-a918-2ea50ae5db50">

**Mobile:**
<img width="329" alt="image" src="https://github.com/user-attachments/assets/7c97e0d3-6391-40e5-9375-f677d89a684c">

Una posible solucion es evitar que se oculten tantos numeros de la columna izquierda y en su lugar ocultar algunas fechas, de esta forma el grafico se verá más alto y se podrá apreciar mejor, además en caso de querer ver alguna fecha en especifico siempre se podrá usar el filtro de la fecha.

**Comment by samuelalvaradodev** [comment]
trabajando en ello

**Comment by samuelalvaradodev** [comment]
cambios realizado
