### ISSUE TITLE
Reporte de clientes

### ISSUE THREAD

**Issue by manuelge** [etruel/fakturo#51]
**Pestaña Sumario**
- Si elige Todos los Clientes deberia mostrar una columna nueva "Cliente" entre el Nro de Factura y el Subtotal.  

**Pestaña Ingresos:** 
- No hay nada. Serían los pagos recibidos del cliente (obtenidos desde los recibos) con un formato similar con datos relevantes del recibo.

**Comment by samuelalvaradodev** [comment]
cambios realizados
