### ISSUE TITLE
Modificación manual del precio final sugerido

### ISSUE THREAD

**Issue by manuelge** [etruel/fakturo#52]
No estaría funcionando la modificación manual de los precios sugeridos según la escala de precios. 

La escala por ejemplo al 18%.  Selecciona Impuesto IVA al 21%

1. Se le pone costo 65.000,00 Moneda peso Argentino
2. El Metabox Precios (Son las escalas) trae:
3. Precio = Costo * escala (18%) = 76.700,00
4. Sugerido = 76.700,00
5. Final = Precio (76.700) * IVA (21%) = 85.904,00

BUG: Al modificar los valores de estos precios tanto sin IVA como el precio final, los valores se guardan pero se siguen mostrando los valores calculados con JS, además en el reporte de productos en la parte de precios las columnas dicen Costo y Precio, pero deberian decir Precio y Precio Final o Precio c/imp.

**Valores calculados con JS**
![image](https://github.com/user-attachments/assets/dd8b15b0-c9fd-4388-8583-20a81fe8c6e7)

**Valor guardado**
<img width="813" alt="image" src="https://github.com/user-attachments/assets/b8c2e9aa-698f-454e-b6e0-29190b780da3">

**Comment by samuelalvaradodev** [comment]
pendiente en revision.
