### ISSUE TITLE
Modificaciones en el reporte de ingresos

### ISSUE THREAD

**Issue by manuelge** [etruel/fakturo#62]
1. ⁠Reporte Ingresos el select de clientes debe ser Select 2 como en los otros. 

2. ⁠Reporte Ingresos: si no se marca Mostrar detalles no muestra nada. Debe mostrar la tabla de totales debajo como lo hace el reporte “Sumario”.

**Comment by samuelalvaradodev** [comment]
cambio realizado

**Comment by manuelge** [comment]
Solucionado
