### ISSUE TITLE
Crear variables para las imagenes de fondo de los templates

### ISSUE THREAD

**Issue by manuelge** [etruel/fakturo#9]
En el print template de las facturas hay una variable llamada "{$fktr_invoice_background_image}" donde está almacenada la URL imagen de fondo que se usa en las facturas.

Ahora que tenemos más templates necesario crear más variables que hagan lo mismo para recibos, proveedores, clientes y productos.

{$fktr_receipt_background_image}
{$fktr_provider_background_image}
{$fktr_client_background_image}
{$fktr_product_background_image}

**Comment by etruel** [comment]
listo en la version 1.0.1
